### ISSUE TITLE
input files

### ISSUE THREAD

**Issue by cruzchue** [evanseitz/ManifoldEM_Python#1]
I was trying to follow the tutorial, but I had problems downloading the "demo" data listed in the PDF tutorial (page 5, 1st paragraph) . I mean, the file is damaged and cannot be unzipped.

Because of this problem, I downloaded the demo data in the "mirrow" link (footnote in the tutorial); but it gives me a different result (see screenshot below). I mean, a circle, not a sphere.   The "mirrow" demo data does not allow me to progress through all tasks.

Can somebody take a look?

Regards;

Eduardo

![circle](https://user-images.githubusercontent.com/20096271/156269876-1415e218-0ab8-46ae-a349-aaa409fb6d54.jpg)

**Comment by evanseitz** [comment]
Hi Eduardo, it's possible the file was damaged during downloading, or something else has changed. In any event, I have no control over the integrity of the data on that site, but am glad to hear the mirror is working for you.

The image you've shown is to be expected since the demo dataset is pruned from a much larger dataset; specifically so that only a great circle is present. To note, a great circle is enough to get decent quality 3D volumes by the end of the demo (i.e., as permitted via the Crowther criterion). If following the tutorial, you should end up with 53 PDs at this point -- you'll see this number in the subwindow after clicking the "PD Thresholding" button located at the bottom left of the "Distribution" tab.
