### ISSUE TITLE
No progress on computing optical flow vectors

### ISSUE THREAD

**Issue by menmt0930** [evanseitz/ManifoldEM_Python#3]
Hello,

I'm testing RyR demo files and it went well until "Anchor Assignment" & "Confirmation of Conformational Coordinates" on "Eigenvectors tab". However, after starting "Finding Conformational Coordinates" temp files were created under "CC" -> "temp" and then the job seemed stuck. Nothing was created under "CC_meas" -> "progress" for 3 days. Also, progress is still 0% on GUI.

On terminal window no error shows up. Just

1.Now computing optical flow vectors for all (selected) PrDs...

Optical flow method: GF-HS

How can I  check what's wrong?

**Comment by evanseitz** [comment]
Hi @menmt0930, 

Since all of the intermediate files leading up to that step are saved, you should be able to force quit the GUI and return to the previous tab for selecting anchors. Perhaps try confirming your choice of anchors again to overwrite anything problematic that may have occurred, and then try to repeat the previously-problematic step from there.

The "Finding CC" step should not take that long, especially for the demo.
